// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { Providers } from "./providers";

import ReactDOM from "react-dom";

import { NextIntlClientProvider, useMessages } from "next-intl";

import AmplifyInit from "@/components/AmplifyInit";

import { TeamWrapper } from "@/components/TeamContext";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";

import GlobalError from "@/app/[lang]/global-error";
import LayoutError from "@/app/[lang]/global-error";
import ErrorBoundary from "next/dist/client/components/error-boundary";

// import AuthCheck from "./components/AuthCheck";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const t = useMessages();

  return (
    <html lang={lang}>
      <body
        className={cn(
          "min-h-screen bg-background text-foreground font-sans antialiased"
        )}
      >
        <AmplifyInit />

        <NextIntlClientProvider messages={t}>
          <Providers>
            <TeamWrapper>{children}</TeamWrapper>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
export default RootLayout;
